const globalColors = {
  'primary-0': '#000000',
  'primary-10': '#201047',
  'primary-20': '#36275D',
  'primary-30': '#4D3D75',
  'primary-40': '#65558F',
  'primary-50': '#7E6EA9',
  'primary-60': '#9887C5',
  'primary-70': '#B3A2E1',
  'primary-80': '#CFBDFE',
  'primary-90': '#E9DDFF',
  'primary-95': '#F6EEFF',
  'primary-99': '#FFFBFF',
  'primary-100': '#FFFFFF',
  'secondary-0': '#000000',
  'secondary-10': '#201047',
  'secondary-20': '#36275D',
  'secondary-30': '#4D3D75',
  'secondary-40': '#65558F',
  'secondary-50': '#7E6EA9',
  'secondary-60': '#9887C5',
  'secondary-70': '#B3A2E1',
  'secondary-80': '#CFBDFE',
  'secondary-90': '#E9DDFF',
  'secondary-95': '#F6EEFF',
  'secondary-99': '#FFFBFF',
  'secondary-100': '#FFFFFF',
  'tertiary-0': '#000000',
  'tertiary-10': '#201047',
  'tertiary-20': '#36275D',
  'tertiary-30': '#4D3D75',
  'tertiary-40': '#65558F',
  'tertiary-50': '#7E6EA9',
  'tertiary-60': '#9887C5',
  'tertiary-70': '#B3A2E1',
  'tertiary-80': '#CFBDFE',
  'tertiary-90': '#E9DDFF',
  'tertiary-95': '#F6EEFF',
  'tertiary-99': '#FFFBFF',
  'tertiary-100': '#FFFFFF',
  'neutral-0': '#000000',
  'neutral-10': '#201047',
  'neutral-20': '#36275D',
  'neutral-30': '#4D3D75',
  'neutral-40': '#65558F',
  'neutral-50': '#7E6EA9',
  'neutral-60': '#9887C5',
  'neutral-70': '#B3A2E1',
  'neutral-80': '#CFBDFE',
  'neutral-90': '#E9DDFF',
  'neutral-95': '#F6EEFF',
  'neutral-99': '#FFFBFF',
  'neutral-100': '#FFFFFF',
  'neutral-variant-0': '#000000',
  'neutral-variant-10': '#201047',
  'neutral-variant-20': '#36275D',
  'neutral-variant-30': '#4D3D75',
  'neutral-variant-40': '#65558F',
  'neutral-variant-50': '#7E6EA9',
  'neutral-variant-60': '#9887C5',
  'neutral-variant-70': '#B3A2E1',
  'neutral-variant-80': '#CFBDFE',
  'neutral-variant-90': '#E9DDFF',
  'neutral-variant-95': '#F6EEFF',
  'neutral-variant-99': '#FFFBFF',
  'neutral-variant-100': '#FFFFFF',
};

export const colors = {
  ...globalColors,
  transparent: 'transparent',
  current: 'currentColor',
  black: '#000000',
  white: '#ffffff',
  'background-light': '#FDF7FF',
  'on-background-light': '#1D1B20',
  'surface-light': '#FDF7FF',
  'surface-dim-light': '#DED8E0',
  'surface-bright-light': '#FDF7FF',
  'surface-container-lowest-light': '#FFFFFF',
  'surface-container-low-light': '#F8F2FA',
  'surface-container-light': '#F2ECF4',
  'surface-container-high-light': '#ECE6EE',
  'surface-container-highest-light': '#E6E0E9',
  'on-surface-light': '#1D1B20',
  'surface-variant-light': '#E7E0EB',
  'on-surface-variant-light': '#49454E',
  'inverse-surface-light': '#322F35',
  'inverse-on-surface-light': '#F5EFF7',
  'outline-light': '#7A757F',
  'outline-variant-light': '#CAC4CF',
  'shadow-light': '#000000',
  'scrim-light': '#000000',
  'surface-tint-light': '#65558F',
  'primary-light': '#65558F',
  'on-primary-light': '#FFFFFF',
  'primary-container-light': '#E9DDFF',
  'on-primary-container-light': '#201047',
  'inverse-primary-light': '#CFBDFE',
  'secondary-light': '#625B71',
  'on-secondary-light': '#FFFFFF',
  'secondary-container-light': '#E8DEF8',
  'on-secondary-container-light': '#1E192B',
  'tertiary-light': '#7E5260',
  'on-tertiary-light': '#FFFFFF',
  'tertiary-container-light': '#FFD9E3',
  'on-tertiary-container-light': '#31101D',
  'error-light': '#BA1A1A',
  'on-error-light': '#FFFFFF',
  'error-container-light': '#FFDAD6',
  'on-error-container-light': '#410002',
  'primary-fixed-light': '#E9DDFF',
  'primary-fixed-dim-light': '#CFBDFE',
  'on-primary-fixed-light': '#201047',
  'on-primary-fixed-variant-light': '#4D3D75',
  'secondary-fixed-light': '#E8DEF8',
  'secondary-fixed-dim-light': '#CBC2DB',
  'on-secondary-fixed-light': '#1E192B',
  'on-secondary-fixed-variant-light': '#4A4458',
  'tertiary-fixed-light': '#FFD9E3',
  'tertiary-fixed-dim-light': '#EFB8C8',
  'on-tertiary-fixed-light': '#31101D',
  'on-tertiary-fixed-variant-light': '#633B48',
  'background-dark': '#141218',
  'on-background-dark': '#E6E0E9',
  'surface-dark': '#141218',
  'surface-dim-dark': '#141218',
  'surface-bright-dark': '#3B383E',
  'surface-container-lowest-dark': '#0F0D13',
  'surface-container-low-dark': '#1D1B20',
  'surface-container-dark': '#211F24',
  'surface-container-high-dark': '#2B292F',
  'surface-container-highest-dark': '#36343A',
  'on-surface-dark': '#E6E0E9',
  'surface-variant-dark': '#49454E',
  'on-surface-variant-dark': '#CAC4CF',
  'inverse-surface-dark': '#E6E0E9',
  'inverse-on-surface-dark': '#322F35',
  'outline-dark': '#948F99',
  'outline-variant-dark': '#49454E',
  'shadow-dark': '#000000',
  'scrim-dark': '#000000',
  'surface-tint-dark': '#CFBDFE',
  'primary-dark': '#CFBDFE',
  'on-primary-dark': '#36275D',
  'primary-container-dark': '#4D3D75',
  'on-primary-container-dark': '#E9DDFF',
  'inverse-primary-dark': '#65558F',
  'secondary-dark': '#CBC2DB',
  'on-secondary-dark': '#332D41',
  'secondary-container-dark': '#4A4458',
  'on-secondary-container-dark': '#E8DEF8',
  'tertiary-dark': '#EFB8C8',
  'on-tertiary-dark': '#4A2532',
  'tertiary-container-dark': '#633B48',
  'on-tertiary-container-dark': '#FFD9E3',
  'error-dark': '#FFB4AB',
  'on-error-dark': '#690005',
  'error-container-dark': '#93000A',
  'on-error-container-dark': '#FFDAD6',
  'primary-fixed-dark': '#E9DDFF',
  'primary-fixed-dim-dark': '#CFBDFE',
  'on-primary-fixed-dark': '#201047',
  'on-primary-fixed-variant-dark': '#4D3D75',
  'secondary-fixed-dark': '#E8DEF8',
  'secondary-fixed-dim-dark': '#CBC2DB',
  'on-secondary-fixed-dark': '#1E192B',
  'on-secondary-fixed-variant-dark': '#4A4458',
  'tertiary-fixed-dark': '#FFD9E3',
  'tertiary-fixed-dim-dark': '#EFB8C8',
  'on-tertiary-fixed-dark': '#31101D',
  'on-tertiary-fixed-variant-dark': '#633B48',
  background: 'rgb(var(--color-background) / <alpha-value> )',
  'on-background': 'rgb(var(--color-on-background) / <alpha-value> )',
  surface: 'rgb(var(--color-surface) / <alpha-value> )',
  'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value> )',
  'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value> )',
  'surface-container-lowest':
    'rgb(var(--color-surface-container-lowest) / <alpha-value> )',
  'surface-container-low':
    'rgb(var(--color-surface-container-low) / <alpha-value> )',
  'surface-container': 'rgb(var(--color-surface-container) / <alpha-value> )',
  'surface-container-high':
    'rgb(var(--color-surface-container-high) / <alpha-value> )',
  'surface-container-highest':
    'rgb(var(--color-surface-container-highest) / <alpha-value> )',
  'on-surface': 'rgb(var(--color-on-surface) / <alpha-value> )',
  'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value> )',
  'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value> )',
  'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value> )',
  'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value> )',
  outline: 'rgb(var(--color-outline) / <alpha-value> )',
  'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value> )',
  shadow: 'rgb(var(--color-shadow) / <alpha-value> )',
  scrim: 'rgb(var(--color-scrim) / <alpha-value> )',
  'surface-tint': 'rgb(var(--color-surface-tint) / <alpha-value> )',
  primary: 'rgb(var(--color-primary) / <alpha-value> )',
  'on-primary': 'rgb(var(--color-on-primary) / <alpha-value> )',
  'primary-container': 'rgb(var(--color-primary-container) / <alpha-value> )',
  'on-primary-container':
    'rgb(var(--color-on-primary-container) / <alpha-value> )',
  'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value> )',
  secondary: 'rgb(var(--color-secondary) / <alpha-value> )',
  'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value> )',
  'secondary-container':
    'rgb(var(--color-secondary-container) / <alpha-value> )',
  'on-secondary-container':
    'rgb(var(--color-on-secondary-container) / <alpha-value> )',
  tertiary: 'rgb(var(--color-tertiary) / <alpha-value> )',
  'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value> )',
  'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value> )',
  'on-tertiary-container':
    'rgb(var(--color-on-tertiary-container) / <alpha-value> )',
  error: 'rgb(var(--color-error) / <alpha-value> )',
  'on-error': 'rgb(var(--color-on-error) / <alpha-value> )',
  'error-container': 'rgb(var(--color-error-container) / <alpha-value> )',
  'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value> )',
  'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value> )',
  'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value> )',
  'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value> )',
  'on-primary-fixed-variant':
    'rgb(var(--color-on-primary-fixed-variant) / <alpha-value> )',
  'secondary-fixed': 'rgb(var(--color-secondary-fixed) / <alpha-value> )',
  'secondary-fixed-dim':
    'rgb(var(--color-secondary-fixed-dim) / <alpha-value> )',
  'on-secondary-fixed': 'rgb(var(--color-on-secondary-fixed) / <alpha-value> )',
  'on-secondary-fixed-variant':
    'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value> )',
  'tertiary-fixed': 'rgb(var(--color-tertiary-fixed) / <alpha-value> )',
  'tertiary-fixed-dim': 'rgb(var(--color-tertiary-fixed-dim) / <alpha-value> )',
  'on-tertiary-fixed': 'rgb(var(--color-on-tertiary-fixed) / <alpha-value> )',
  'on-tertiary-fixed-variant':
    'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value> )',
};

export const result = {
  background: 'rgb(var(--color-background) / <alpha-value> )',
  'background-dark': '#141218',
  'background-light': '#FDF7FF',
  black: '#000000',
  current: 'currentColor',
  error: 'rgb(var(--color-error) / <alpha-value> )',
  'error-container': 'rgb(var(--color-error-container) / <alpha-value> )',
  'error-container-dark': '#93000A',
  'error-container-light': '#FFDAD6',
  'error-dark': '#FFB4AB',
  'error-light': '#BA1A1A',
  'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value> )',
  'inverse-on-surface-dark': '#322F35',
  'inverse-on-surface-light': '#F5EFF7',
  'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value> )',
  'inverse-primary-dark': '#65558F',
  'inverse-primary-light': '#CFBDFE',
  'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value> )',
  'inverse-surface-dark': '#E6E0E9',
  'inverse-surface-light': '#322F35',
  'neutral-0': '#000000',
  'neutral-10': '#201047',
  'neutral-100': '#FFFFFF',
  'neutral-20': '#36275D',
  'neutral-30': '#4D3D75',
  'neutral-40': '#65558F',
  'neutral-50': '#7E6EA9',
  'neutral-60': '#9887C5',
  'neutral-70': '#B3A2E1',
  'neutral-80': '#CFBDFE',
  'neutral-90': '#E9DDFF',
  'neutral-95': '#F6EEFF',
  'neutral-99': '#FFFBFF',
  'neutral-variant-0': '#000000',
  'neutral-variant-10': '#201047',
  'neutral-variant-100': '#FFFFFF',
  'neutral-variant-20': '#36275D',
  'neutral-variant-30': '#4D3D75',
  'neutral-variant-40': '#65558F',
  'neutral-variant-50': '#7E6EA9',
  'neutral-variant-60': '#9887C5',
  'neutral-variant-70': '#B3A2E1',
  'neutral-variant-80': '#CFBDFE',
  'neutral-variant-90': '#E9DDFF',
  'neutral-variant-95': '#F6EEFF',
  'neutral-variant-99': '#FFFBFF',
  'on-background': 'rgb(var(--color-on-background) / <alpha-value> )',
  'on-background-dark': '#E6E0E9',
  'on-background-light': '#1D1B20',
  'on-error': 'rgb(var(--color-on-error) / <alpha-value> )',
  'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value> )',
  'on-error-container-dark': '#FFDAD6',
  'on-error-container-light': '#410002',
  'on-error-dark': '#690005',
  'on-error-light': '#FFFFFF',
  'on-primary': 'rgb(var(--color-on-primary) / <alpha-value> )',
  'on-primary-container':
    'rgb(var(--color-on-primary-container) / <alpha-value> )',
  'on-primary-container-dark': '#E9DDFF',
  'on-primary-container-light': '#201047',
  'on-primary-dark': '#36275D',
  'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value> )',
  'on-primary-fixed-dark': '#201047',
  'on-primary-fixed-light': '#201047',
  'on-primary-fixed-variant':
    'rgb(var(--color-on-primary-fixed-variant) / <alpha-value> )',
  'on-primary-fixed-variant-dark': '#4D3D75',
  'on-primary-fixed-variant-light': '#4D3D75',
  'on-primary-light': '#FFFFFF',
  'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value> )',
  'on-secondary-container':
    'rgb(var(--color-on-secondary-container) / <alpha-value> )',
  'on-secondary-container-dark': '#E8DEF8',
  'on-secondary-container-light': '#1E192B',
  'on-secondary-dark': '#332D41',
  'on-secondary-fixed': 'rgb(var(--color-on-secondary-fixed) / <alpha-value> )',
  'on-secondary-fixed-dark': '#1E192B',
  'on-secondary-fixed-light': '#1E192B',
  'on-secondary-fixed-variant':
    'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value> )',
  'on-secondary-fixed-variant-dark': '#4A4458',
  'on-secondary-fixed-variant-light': '#4A4458',
  'on-secondary-light': '#FFFFFF',
  'on-surface': 'rgb(var(--color-on-surface) / <alpha-value> )',
  'on-surface-dark': '#E6E0E9',
  'on-surface-light': '#1D1B20',
  'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value> )',
  'on-surface-variant-dark': '#CAC4CF',
  'on-surface-variant-light': '#49454E',
  'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value> )',
  'on-tertiary-container':
    'rgb(var(--color-on-tertiary-container) / <alpha-value> )',
  'on-tertiary-container-dark': '#FFD9E3',
  'on-tertiary-container-light': '#31101D',
  'on-tertiary-dark': '#4A2532',
  'on-tertiary-fixed': 'rgb(var(--color-on-tertiary-fixed) / <alpha-value> )',
  'on-tertiary-fixed-dark': '#31101D',
  'on-tertiary-fixed-light': '#31101D',
  'on-tertiary-fixed-variant':
    'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value> )',
  'on-tertiary-fixed-variant-dark': '#633B48',
  'on-tertiary-fixed-variant-light': '#633B48',
  'on-tertiary-light': '#FFFFFF',
  outline: 'rgb(var(--color-outline) / <alpha-value> )',
  'outline-dark': '#948F99',
  'outline-light': '#7A757F',
  'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value> )',
  'outline-variant-dark': '#49454E',
  'outline-variant-light': '#CAC4CF',
  primary: 'rgb(var(--color-primary) / <alpha-value> )',
  'primary-0': '#000000',
  'primary-10': '#201047',
  'primary-100': '#FFFFFF',
  'primary-20': '#36275D',
  'primary-30': '#4D3D75',
  'primary-40': '#65558F',
  'primary-50': '#7E6EA9',
  'primary-60': '#9887C5',
  'primary-70': '#B3A2E1',
  'primary-80': '#CFBDFE',
  'primary-90': '#E9DDFF',
  'primary-95': '#F6EEFF',
  'primary-99': '#FFFBFF',
  'primary-container': 'rgb(var(--color-primary-container) / <alpha-value> )',
  'primary-container-dark': '#4D3D75',
  'primary-container-light': '#E9DDFF',
  'primary-dark': '#CFBDFE',
  'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value> )',
  'primary-fixed-dark': '#E9DDFF',
  'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value> )',
  'primary-fixed-dim-dark': '#CFBDFE',
  'primary-fixed-dim-light': '#CFBDFE',
  'primary-fixed-light': '#E9DDFF',
  'primary-light': '#65558F',
  scrim: 'rgb(var(--color-scrim) / <alpha-value> )',
  'scrim-dark': '#000000',
  'scrim-light': '#000000',
  secondary: 'rgb(var(--color-secondary) / <alpha-value> )',
  'secondary-0': '#000000',
  'secondary-10': '#201047',
  'secondary-100': '#FFFFFF',
  'secondary-20': '#36275D',
  'secondary-30': '#4D3D75',
  'secondary-40': '#65558F',
  'secondary-50': '#7E6EA9',
  'secondary-60': '#9887C5',
  'secondary-70': '#B3A2E1',
  'secondary-80': '#CFBDFE',
  'secondary-90': '#E9DDFF',
  'secondary-95': '#F6EEFF',
  'secondary-99': '#FFFBFF',
  'secondary-container':
    'rgb(var(--color-secondary-container) / <alpha-value> )',
  'secondary-container-dark': '#4A4458',
  'secondary-container-light': '#E8DEF8',
  'secondary-dark': '#CBC2DB',
  'secondary-fixed': 'rgb(var(--color-secondary-fixed) / <alpha-value> )',
  'secondary-fixed-dark': '#E8DEF8',
  'secondary-fixed-dim':
    'rgb(var(--color-secondary-fixed-dim) / <alpha-value> )',
  'secondary-fixed-dim-dark': '#CBC2DB',
  'secondary-fixed-dim-light': '#CBC2DB',
  'secondary-fixed-light': '#E8DEF8',
  'secondary-light': '#625B71',
  shadow: 'rgb(var(--color-shadow) / <alpha-value> )',
  'shadow-dark': '#000000',
  'shadow-light': '#000000',
  surface: 'rgb(var(--color-surface) / <alpha-value> )',
  'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value> )',
  'surface-bright-dark': '#3B383E',
  'surface-bright-light': '#FDF7FF',
  'surface-container': 'rgb(var(--color-surface-container) / <alpha-value> )',
  'surface-container-dark': '#211F24',
  'surface-container-high':
    'rgb(var(--color-surface-container-high) / <alpha-value> )',
  'surface-container-high-dark': '#2B292F',
  'surface-container-high-light': '#ECE6EE',
  'surface-container-highest':
    'rgb(var(--color-surface-container-highest) / <alpha-value> )',
  'surface-container-highest-dark': '#36343A',
  'surface-container-highest-light': '#E6E0E9',
  'surface-container-light': '#F2ECF4',
  'surface-container-low':
    'rgb(var(--color-surface-container-low) / <alpha-value> )',
  'surface-container-low-dark': '#1D1B20',
  'surface-container-low-light': '#F8F2FA',
  'surface-container-lowest':
    'rgb(var(--color-surface-container-lowest) / <alpha-value> )',
  'surface-container-lowest-dark': '#0F0D13',
  'surface-container-lowest-light': '#FFFFFF',
  'surface-dark': '#141218',
  'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value> )',
  'surface-dim-dark': '#141218',
  'surface-dim-light': '#DED8E0',
  'surface-light': '#FDF7FF',
  'surface-tint': 'rgb(var(--color-surface-tint) / <alpha-value> )',
  'surface-tint-dark': '#CFBDFE',
  'surface-tint-light': '#65558F',
  'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value> )',
  'surface-variant-dark': '#49454E',
  'surface-variant-light': '#E7E0EB',
  tertiary: 'rgb(var(--color-tertiary) / <alpha-value> )',
  'tertiary-0': '#000000',
  'tertiary-10': '#201047',
  'tertiary-100': '#FFFFFF',
  'tertiary-20': '#36275D',
  'tertiary-30': '#4D3D75',
  'tertiary-40': '#65558F',
  'tertiary-50': '#7E6EA9',
  'tertiary-60': '#9887C5',
  'tertiary-70': '#B3A2E1',
  'tertiary-80': '#CFBDFE',
  'tertiary-90': '#E9DDFF',
  'tertiary-95': '#F6EEFF',
  'tertiary-99': '#FFFBFF',
  'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value> )',
  'tertiary-container-dark': '#633B48',
  'tertiary-container-light': '#FFD9E3',
  'tertiary-dark': '#EFB8C8',
  'tertiary-fixed': 'rgb(var(--color-tertiary-fixed) / <alpha-value> )',
  'tertiary-fixed-dark': '#FFD9E3',
  'tertiary-fixed-dim': 'rgb(var(--color-tertiary-fixed-dim) / <alpha-value> )',
  'tertiary-fixed-dim-dark': '#EFB8C8',
  'tertiary-fixed-dim-light': '#EFB8C8',
  'tertiary-fixed-light': '#FFD9E3',
  'tertiary-light': '#7E5260',
  transparent: 'transparent',
  white: '#ffffff',
};

export const state = {
  statePrefix: 'state',
  disabledStyles: {
    textOpacity: 0.38,
    backgroundOpacity: 0.12,
  },
  transition: {
    duration: 150,
  },
};
