name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## :warning: We use GitHub Issues to track bug reports, feature requests and regressions

        If you are not sure that your issue is a bug, use our [Discord community](https://discord.com/invite/bt2h5RCp77)

        ---
        
  - type: checkboxes
    attributes:
      label: "Is there an existing issue that is already proposing this?"
      description: "Please search [here](https://github.com/Udixio/tailwind-material/issues) to see if an issue already exists for the feature you are requesting"
      options:
      - label: "I have searched the existing issues"
        required: true

  - type: checkboxes
    attributes:
      label: "Latest version"
      description: "We roll bug fixes, performance enhancements, and other improvements into new releases."
      options:
        - label: "I have tested the latest version"
          required: true
  - type: textarea
    attributes:
      label: Summary 💡
      description: "Describe how it should work."
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Examples 🌈"
      description: "Provide a link to the Material Design specification, other implementations, or screenshots of the expected behavior."
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Motivation 🔦"
      description: "What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world."
